            - name: AppScan SAST
  # You may pin to the exact commit or the version.
  # uses: alphayax/appscan-sast-action@6075e1382672511f58d00c6712d7f4206399f8c6
  uses: alphayax/appscan-sast-action@v1
  with:
    # ASoC Key Secret
    api-secret: 
    # ASoC Key Id
    api-id: 
    # Application Id (guid)
    application-id: 
          
